class_name UIStyle
extends RefCounted
## Shared look & feel for every Astro Neighbor UI scene: palette, sizes, StyleBox builders,
## pop / bump / wobble animations and guarded UI sounds.
## The Theme resource lives at THEME_PATH and is generated by build_theme.gd:
##   godot --headless --path . -s res://src/ui/theme/build_theme.gd

const THEME_PATH := "res://src/ui/theme/astro_theme.tres"
## Baloo 2 (SIL Open Font License 1.1, licence bundled beside it). Chosen over the old system
## stack because a SystemFont resolves through the host, and in a browser export "Arial
## Rounded MT Bold" is simply not there — the web build fell back to a plain sans and lost
## the rounded character the whole UI is built on. A bundled file renders identically on
## desktop, phone and web.
const FONT_PATH := "res://assets/fonts/Baloo2.ttf"
## Fallback only, for the (impossible) case where the bundled file fails to load.
const FONT_NAMES: PackedStringArray = ["Arial Rounded MT Bold", "Avenir Next", "Helvetica Neue"]

# ----------------------------------------------------------------------------- palette (STYLE_GUIDE.md)
## MOONSTONE. The UI used to be cream panels with brown text, which read as a direct lift of the
## reference game. This palette keeps every shape, radius and outline weight the same and changes
## only the colour: pale cool stone, dark slate text, one amber accent.
##
## WHY GREY. The UI has to sit on four very different worlds — green home, violet Zorp, chrome Bolt,
## sand hub — and grey is the only hue that cannot clash with any of them, so ONE palette covers
## them all and any planet added later. It also keeps the decorations the most colourful thing on
## screen, which matters in a game about decorating.
##
## The names below are historical (CREAM, TEXT_BROWN) and are left alone on purpose: they are read
## from dozens of call sites, and renaming them would be a large diff that changes no behaviour.
## Read them as "panel fill" and "body text".
##
## Panel fills stay capped at HSV value 0.92. At V 0.99 the HUD alone put 7-9% of every gameplay
## frame over the blown-highlight threshold (R2.6 gate is < 5%), because the panels cover 7-9% of
## the screen.
const CREAM := Color("#e9eaf1")
const CREAM_EDGE := Color("#9295ac")
const CREAM_DEEP := Color("#dcdee9")
## Inset wells (the item grid, the details column). Pulled down from CARD_FILL so a card still reads
## as a raised tile against it — the pair keeps the same ~0.08 luma step it always had.
const CREAM_INSET := Color("#d5d8e4")
const WHITE := Color("#fbfcff")
## Fill of an item CARD and of a text input. `WHITE` measures luma 0.99, and a stocked shop is
## mostly cards, which is why a shop frame measured 12-18% blown (R2.6: "no near-clipping whites -
## cap ~0.92"). CARD_FILL measures 0.91. WHITE is kept for TEXT and outlines, where the area is a
## few hundred pixels and the contrast is the whole point.
const CARD_FILL := Color("#eef0f6")
## Body text. Dark slate, not black: it has the same softness brown had, without the warmth that
## made the old UI read as the reference game.
const TEXT_BROWN := Color("#2c2f42")
const TEXT_SOFT := Color("#6d7288")
const NAME_BLUE := Color("#4c5b8c")
const NAME_BLUE_EDGE := Color("#39456e")
## THE one accent, used for the confirm action and nothing else. Amber reads as warm and
## unmistakable against cool grey, and it is the only saturated colour the chrome is allowed.
const YELLOW := Color("#f0a64a")
const YELLOW_EDGE := Color("#c9822f")
const ORANGE := Color("#ef7f52")
const ORANGE_EDGE := Color("#c9613a")
const NAVY := Color("#1b1f33")
## Stardust stays gold. It is the currency, not chrome, and it is what the accent points at.
const STARDUST := Color("#ffe27a")
const STARDUST_EDGE := Color("#e0a83a")
const STARDUST_SPARKLE := Color("#fff6c8")
const GREEN := Color("#6fc47f")
const GREEN_EDGE := Color("#4fa663")
const RED := Color("#e8646f")
const BACKDROP := Color(0.07, 0.08, 0.16, 0.46)
## Focus ring colour for warm / amber fills, where the default ring would be invisible.
const FOCUS_ON_WARM := Color("#4a2a08")

const RARITY_COLORS := {
	"common": Color("#8fbf8f"),
	"uncommon": Color("#4fb3ff"),
	"rare": Color("#b58cff"),
	"legendary": Color("#ffb347"),
}

# ----------------------------------------------------------------------------- sizes
const SIZE_BODY := 22
const SIZE_SMALL := 17
const SIZE_HINT := 15
const SIZE_TITLE := 40
const SIZE_HEADER := 28
const SIZE_DIALOGUE := 26
const RADIUS := 28
const RADIUS_CARD := 22
## StyleBoxFlat clamps radii to half the rect size, so a huge radius is a perfect pill.
const RADIUS_PILL := 400
const SHADOW_COLOR := Color(0.32, 0.20, 0.06, 0.16)

const POP_DURATION := 0.25
const FOCUS_SCALE := 1.05

static var _sfx_exists: Dictionary = {}

# ----------------------------------------------------------------------------- theme / font
## The shared Theme resource (ResourceLoader caches it; no static reference is kept so nothing leaks at exit).
static func theme() -> Theme:
	if ResourceLoader.exists(THEME_PATH):
		return load(THEME_PATH) as Theme
	push_error("UIStyle: theme missing at %s (run build_theme.gd)" % THEME_PATH)
	return Theme.new()

## The rounded UI font. Prefers the BUNDLED Baloo 2 file — a SystemFont resolves through the
## host, and in a browser export the old "Arial Rounded MT Bold" simply is not present, so
## the web build silently fell back to a plain sans and lost the rounded character the whole
## UI is built on. Falls back to the system stack only if the file is missing.
static func ui_font() -> Font:
	if ResourceLoader.exists(FONT_PATH):
		var ff := load(FONT_PATH) as FontFile
		if ff != null:
			ff.antialiasing = TextServer.FONT_ANTIALIASING_GRAY
			ff.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_AUTO
			ff.hinting = TextServer.HINTING_LIGHT
			return ff
	var sf := SystemFont.new()
	sf.font_names = FONT_NAMES
	sf.antialiasing = TextServer.FONT_ANTIALIASING_GRAY
	return sf


## The rounded UI font used everywhere.
static func font() -> Font:
	var t := theme()
	if t.default_font != null:
		return t.default_font
	return ui_font()

# ----------------------------------------------------------------------------- style boxes
## A rounded cream panel with a soft drop shadow and a slightly darker border.
static func make_panel_style(color: Color = CREAM, radius: int = RADIUS, border_color: Color = CREAM_EDGE,
		border_width: int = 3, shadow_size: int = 10, margin: float = 20.0) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = color
	sb.set_corner_radius_all(radius)
	sb.corner_detail = 14
	sb.anti_aliasing = true
	sb.anti_aliasing_size = 1.0
	sb.set_border_width_all(border_width)
	sb.border_color = border_color
	sb.border_blend = false
	sb.shadow_size = shadow_size
	sb.shadow_color = SHADOW_COLOR
	sb.shadow_offset = Vector2(0.0, 4.0) if shadow_size > 0 else Vector2.ZERO
	sb.set_content_margin_all(margin)
	return sb

## Pill (fully rounded) variant of make_panel_style with separate horizontal / vertical margins.
static func make_pill_style(color: Color = CREAM, border_color: Color = CREAM_EDGE, border_width: int = 3,
		shadow_size: int = 6, margin_h: float = 24.0, margin_v: float = 10.0) -> StyleBoxFlat:
	var sb := make_panel_style(color, RADIUS_PILL, border_color, border_width, shadow_size, margin_h)
	sb.content_margin_top = margin_v
	sb.content_margin_bottom = margin_v
	return sb

## Focus ring drawn around a control (draw_center off, expands outside the rect).
## `color` must contrast with the control's own fill — a yellow ring on a yellow pill is invisible,
## so warm/yellow buttons pass FOCUS_ON_WARM instead (see build_theme.gd).
static func make_focus_style(radius: int = RADIUS_PILL, width: int = 4, expand: float = 4.0,
		color: Color = YELLOW) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.draw_center = false
	sb.set_corner_radius_all(radius)
	sb.corner_detail = 14
	sb.anti_aliasing = true
	sb.set_border_width_all(width)
	sb.border_color = color
	sb.set_expand_margin_all(expand)
	return sb

## An invisible style box (used to blank out container backgrounds).
static func make_empty_style() -> StyleBoxEmpty:
	return StyleBoxEmpty.new()

# ----------------------------------------------------------------------------- layout helpers
## Sets pivot to the control's center so scale animations grow from the middle.
static func center_pivot(control: Control) -> void:
	control.pivot_offset = control.size * 0.5

## Anchors a control to the center of its parent with a fixed size.
static func center_control(control: Control, box: Vector2, offset: Vector2 = Vector2.ZERO) -> void:
	control.set_anchors_preset(Control.PRESET_CENTER)
	control.anchor_left = 0.5
	control.anchor_right = 0.5
	control.anchor_top = 0.5
	control.anchor_bottom = 0.5
	control.offset_left = -box.x * 0.5 + offset.x
	control.offset_right = box.x * 0.5 + offset.x
	control.offset_top = -box.y * 0.5 + offset.y
	control.offset_bottom = box.y * 0.5 + offset.y
	control.pivot_offset = box * 0.5

## Creates a Label with a theme variation and optional overrides.
static func make_label(text: String, variation: String = "", align: HorizontalAlignment = HORIZONTAL_ALIGNMENT_LEFT) -> Label:
	var l := Label.new()
	l.text = text
	if variation != "":
		l.theme_type_variation = variation
	l.horizontal_alignment = align
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return l

## Creates a pill Button wired with focus pop + tick sound.
static func make_button(text: String, variation: String = "Pill", min_width: float = 0.0) -> Button:
	var b := Button.new()
	b.text = text
	if min_width > 0.0:
		b.custom_minimum_size = Vector2(min_width, 0.0)
	setup_button(b, variation)
	return b

## Wires a Button: pill variation, hover = focus, focus = 1.05 scale pop + tick sound.
static func setup_button(b: Button, variation: String = "Pill") -> void:
	b.theme_type_variation = variation
	b.focus_mode = Control.FOCUS_ALL
	b.mouse_entered.connect(func() -> void:
		if not b.disabled and b.is_visible_in_tree():
			b.grab_focus())
	b.focus_entered.connect(func() -> void: _on_button_focus(b))
	b.focus_exited.connect(func() -> void: _on_button_unfocus(b))
	b.resized.connect(func() -> void: center_pivot(b))
	b.pressed.connect(func() -> void: play_confirm())
	center_pivot(b)

static func _on_button_focus(b: Control) -> void:
	center_pivot(b)
	var t := b.create_tween()
	t.tween_property(b, "scale", Vector2.ONE * FOCUS_SCALE, 0.16).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	play_tick()

static func _on_button_unfocus(b: Control) -> void:
	var t := b.create_tween()
	t.tween_property(b, "scale", Vector2.ONE, 0.12).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)

# ----------------------------------------------------------------------------- animation
## Panel pop-in: scale 0.9 -> 1 with a back ease, fade in. Returns the tween.
static func pop_in(control: Control, duration: float = POP_DURATION, from_scale: float = 0.9) -> Tween:
	center_pivot(control)
	control.visible = true
	control.scale = Vector2.ONE * from_scale
	control.modulate.a = 0.0
	var t := control.create_tween().set_parallel(true)
	t.tween_property(control, "scale", Vector2.ONE, duration).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	t.tween_property(control, "modulate:a", 1.0, duration * 0.6).set_trans(Tween.TRANS_SINE)
	return t

## Panel pop-out: scale -> 0.9 and fade, then hides the control. Returns the tween.
static func pop_out(control: Control, duration: float = 0.18, to_scale: float = 0.9) -> Tween:
	center_pivot(control)
	var t := control.create_tween().set_parallel(true)
	t.tween_property(control, "scale", Vector2.ONE * to_scale, duration).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN)
	t.tween_property(control, "modulate:a", 0.0, duration).set_trans(Tween.TRANS_SINE)
	t.chain().tween_callback(func() -> void:
		control.visible = false
		control.scale = Vector2.ONE
		control.modulate.a = 1.0)
	return t

## Quick elastic scale punch (counters, badges).
static func bump(control: Control, amount: float = 1.25, duration: float = 0.45) -> void:
	center_pivot(control)
	control.scale = Vector2.ONE * amount
	var t := control.create_tween()
	t.tween_property(control, "scale", Vector2.ONE, duration).set_trans(Tween.TRANS_ELASTIC).set_ease(Tween.EASE_OUT)

## Rotation wobble — safe for children of containers (position is untouched).
static func wobble(control: Control, degrees: float = 5.0, duration: float = 0.36) -> void:
	center_pivot(control)
	var t := control.create_tween()
	var steps := 5
	for i in steps:
		var a := deg_to_rad(degrees) * (1.0 - float(i) / float(steps)) * (1.0 if i % 2 == 0 else -1.0)
		t.tween_property(control, "rotation", a, duration / float(steps + 1)).set_trans(Tween.TRANS_SINE)
	t.tween_property(control, "rotation", 0.0, duration / float(steps + 1)).set_trans(Tween.TRANS_SINE)

## Horizontal shake — only for controls that are NOT managed by a Container.
static func shake(control: Control, strength: float = 8.0, duration: float = 0.32) -> void:
	var origin_x := control.position.x
	var t := control.create_tween()
	var steps := 6
	for i in steps:
		var off := strength * (1.0 - float(i) / float(steps)) * (1.0 if i % 2 == 0 else -1.0)
		t.tween_property(control, "position:x", origin_x + off, duration / float(steps + 1))
	t.tween_property(control, "position:x", origin_x, duration / float(steps + 1))

# ----------------------------------------------------------------------------- sound (guarded: missing files stay silent)
## Mirrors AudioManager's folders (kept local so this script also compiles in tool scripts without autoloads).
const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"

## The AudioManager autoload, looked up at runtime (null in tool scripts).
static func _audio() -> Node:
	var loop := Engine.get_main_loop() as SceneTree
	if loop == null or loop.root == null:
		return null
	return loop.root.get_node_or_null("AudioManager")

## True if assets/audio/sfx/<name>.wav|ogg exists. Cached.
static func sfx_exists(sfx_name: String) -> bool:
	if not _sfx_exists.has(sfx_name):
		_sfx_exists[sfx_name] = ResourceLoader.exists(SFX_DIR + sfx_name + ".wav") \
			or ResourceLoader.exists(SFX_DIR + sfx_name + ".ogg")
	return bool(_sfx_exists[sfx_name])

## Plays a UI sound through AudioManager if the file exists.
static func play_sfx(sfx_name: String, volume_db: float = 0.0) -> void:
	if not sfx_exists(sfx_name):
		return
	var audio := _audio()
	if audio != null:
		audio.call("play_sfx", sfx_name, volume_db)

static func play_tick() -> void:
	play_sfx("ui_tick", -6.0)

static func play_confirm() -> void:
	play_sfx("ui_confirm")

static func play_cancel() -> void:
	play_sfx("ui_cancel")

static func play_open() -> void:
	play_sfx("ui_open")

static func play_close() -> void:
	play_sfx("ui_close")

## COMPATIBILITY: one short comms gesture for a neighbour id ("zorp") or a legacy profile ("alien").
## Dialogue no longer calls this per letter - it uses the comms_* entry points below. The old guard
## (voice_<profile>_0 must exist) is gone because the ten comms voices have no _0 file;
## AudioManager.play_voice_blip checks for its own files.
static func play_voice_blip(profile: String) -> void:
	var audio := _audio()
	if audio != null:
		audio.call("play_voice_blip", profile)

## COMMS VOICE entry points for the dialogue box - see AudioManager "comms voices" for the scheme
## (key-up, one gesture per phrase, squelch / "over"). Guarded like every sound here: without the
## AudioManager autoload they do nothing and comms_voice_for() answers "" (silent).
static func comms_voice_for(profile: String, speaker: String = "", line_index: int = 0) -> String:
	var audio := _audio()
	return str(audio.call("comms_voice_for", profile, speaker, line_index)) if audio != null else ""

static func comms_open_line(voice: String, line: String, closes_turn: bool) -> void:
	var audio := _audio()
	if audio != null:
		audio.call("comms_open_line", voice, line, closes_turn)

static func comms_reveal(visible_chars: int) -> void:
	var audio := _audio()
	if audio != null:
		audio.call("comms_reveal", visible_chars)

static func comms_close_line(cut: bool) -> void:
	var audio := _audio()
	if audio != null:
		audio.call("comms_close_line", cut)

static func comms_hold(paused: bool) -> void:
	var audio := _audio()
	if audio != null:
		audio.call("comms_hold", paused)

## Starts a music track if it exists.
static func play_music(track: String) -> void:
	if not (ResourceLoader.exists(MUSIC_DIR + track + ".ogg") or ResourceLoader.exists(MUSIC_DIR + track + ".wav")):
		return
	var audio := _audio()
	if audio != null:
		audio.call("play_music", track)

# ----------------------------------------------------------------------------- text helpers
## "9:30 AM" style clock string from a float hour.
static func format_clock(hour_float: float) -> String:
	var h := int(floor(hour_float)) % 24
	var m := int(floor((hour_float - floor(hour_float)) * 60.0))
	var suffix := "AM" if h < 12 else "PM"
	var h12 := h % 12
	if h12 == 0:
		h12 = 12
	return "%d:%02d %s" % [h12, m, suffix]

## Title-cases an id like "deco_moon_lamp" -> "Moon Lamp" (used when the Catalog has no entry).
static func pretty_id(id: String) -> String:
	var parts := id.split("_", false)
	var out: PackedStringArray = []
	for p in parts:
		if p in ["deco", "item", "mat"]:
			continue
		out.append(p.capitalize())
	return " ".join(out) if out.size() > 0 else id
